sudo: required
services:
    - docker

before_install:
    - docker build -t bmcavestany/docker-react -f Dockerfile.dev .

    script:
        - docker run -e CI=true bmcavestany/docker-react npm run test